title: Geonorge - docs
description: Dokumentasjon for brukerne av Geonorge
theme: just-the-docs
logo: "/assets/img/geonorge-logo.png"
favicon_ico: "/assets/img/favicon.ico"

url: https://kartverket.github.io/docs.geonorge.no/

aux_links: 
  Template Repository: https://github.com/kartverket/docs.geonorge.no
