title: Geonorge wiki som skal bli docs, men docs er opptatt
description: Testttt
theme: just-the-docs

url: https://kartverket.github.io/wiki.geonorge.no/

aux_links: 
  Template Repository: https://github.com/kartverket/wiki.geonorge.no
