title: Geonorge - docs
description: Testttt
theme: just-the-docs
logo: "/assets/img/geonorge-logo.png"

url: https://kartverket.github.io/wiki.geonorge.no/

aux_links: 
  Template Repository: https://github.com/kartverket/wiki.geonorge.no
